apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-preview-generator
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: BennyG93
        # The Github repository
        repo: argocd-appsetofapps-example
        # Reference to a Secret containing an access token. (optional)
        # tokenRef:
        #   secretName: github-token
        #   key: token
        # Labels is used to filter the PRs that you want to target. (optional)
        # labels:
        # - preview
  template:
    metadata:
      name: 'example-pr-{{number}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/BennyG93/argocd-appsetofapps-example.git
        path: apps
        targetRevision: '{{branch}}'
        helm:
          parameters:
          - name: "project"
            value: 'example-pr-{{number}}'
          - name: "git.sha_hash"
            value: '{{head_sha}}'
          - name: "git.branch_name"
            value: '{{branch}}'
          - name: "git.pr_number"
            value: '{{number}}'
      syncPolicy:
        automated: {}
